---
- name: Install zsh packages
  become: True
  package:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: Ensure configuration directories exist
  become: True
  become_user: "{{ zsh_user }}"
  file:
    path: "~/.{{ item }}"
    state: directory
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
  with_items:
    - "zshrc.d"
    - "zprofile.d"

- name: Configure .zshrc and .zprofile
  become: True
  become_user: "{{ zsh_user }}"
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
  with_items:
    - zshrc
    - zprofile

- name: Configure base templates for zshrc
  become: True
  become_user: "{{ zsh_user }}"
  template:
    src: "zshrc.d/{{ item }}.j2"
    dest: "~/.zshrc.d/{{ item }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
  with_items:
    - 00-dircolors
    - 10-compinit
    - 20-base
    - 90-zsh-plugins

- name: Configure base templates for zprofile
  become: True
  become_user: "{{ zsh_user }}"
  template:
    src: "zprofile.d/{{ item }}.j2"
    dest: "~/.zprofile.d/{{ item }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
  with_items:
    - 50-empty

- name: Set zsh as default shell
  become: True
  user:
    name: "{{ zsh_user }}"
    shell: /usr/bin/zsh
