---
- name: Converge
  hosts: all
  roles:
    - role: zsh
      vars:
        zsh_user: root
# TODO: This use case is not supported (yet), see
# https://github.com/threefx/ansible-zsh/issues/1 for more information
#    - role: zsh
#      vars:
#        zsh_user: testuser
