---
- name: Prepare
  hosts: all
  tasks:
    - name: Create test user
      user:
        name: testuser
        home: /home/testuser
    # Sadly, docker images often have stale caches, especially for Arch Linux
    - name: Update package caches
      include_role:
        name: update-packages
